UD_CBV/UD_CBV/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("store/", include("store.urls")),
    path("accounts/", include("accounts.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UD_CBV/accounts/urls.py
from django.urls import path
from .views import (
    RegistUserView, HomeView, UserLoginView, UserLogoutView
)

app_name="accounts"
urlpatterns = [
    path("home/", HomeView.as_view(), name="home"),
    path("regist/", RegistUserView.as_view(), name="regist"),
    path("user_login/", UserLoginView.as_view(),name="user_login"),
    path("user_logout/",UserLogoutView.as_view(), name="user_logout"),
    
]

UD_CBV/store/urls.py
from django.urls import path
from .views import (BookCreateView, BookDeleteView, BookDetailView, BookFormView, BookRedirectView, BookUpdateView, IndexView, HomeView, BookListView, delete_picture)
#from django.views.generic.base import TemplateView
from django.views.generic.base import RedirectView

app_name = "store"

urlpatterns = [
    path("index/", IndexView.as_view(), name="index"),
    #path("home/", TemplateView.as_view(template_name="home.html"),name="home")
    path("home/<name>", HomeView.as_view(), name="home"),
    path("detail_book/<int:pk>", BookDetailView.as_view(), name="detail_book"),
    path("list_books/", BookListView.as_view(), name="list_books"),
    path("list_books/<name>", BookListView.as_view(), name="list_books"),
    path("add_book/", BookCreateView.as_view(), name="add_book"),
    path("edit_book/<int:pk>", BookUpdateView.as_view(), name="edit_book"),
    path("delete_book/<int:pk>", BookDeleteView.as_view(), name="delete_book"),
    path("book_form/", BookFormView.as_view(), name="book_form"),
    path("google/", RedirectView.as_view(url="https://google.co.jp"), name="google"),
    path("book_redirect_view/", BookRedirectView.as_view(), name="book_redirect_view"),
    path("book_redirect_view/<int:pk>", BookRedirectView.as_view(), name="book_redirect_view"),
    path("delete_picture/<int:pk>", delete_picture, name="delete_picture"),
    




]

UD_CBV/accounts/models.py
from django.db import models
#ユーザをカスタマイズ用のモデルを作成する
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin

)
from django.urls import reverse_lazy
# Create your models here.

#create用
class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError("Enter Email")
        user = self.model(
            username=username,
            email = email
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

#カスタマイズ用
class Users(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=150)
    email = models.EmailField(max_length=255, unique=True)
    is_active=models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
#ユーザを一意に識別
    USERNAME_FIELD = "email"
#スーパーユーザ作成に必要なフィールド
    REQUIRED_FIELDS = ["username"]

    objects = UserManager()

    def get_absolute_url(get):
        return reverse_lazy("accounts:home")

UD_CBV/accounts/forms.py
from django import forms
from .models import Users
from django.contrib.auth.password_validation import validate_password

class RegistForm(forms.ModelForm):
    username = forms.CharField(label="名前")
    age = forms.IntegerField(label="年齢")
    email = forms.EmailField(label="メールアドレス")
    password = forms.CharField(label="パスワード", widget=forms.PasswordInput())
    class Meta:
        model = Users
        fields = ["username", "age", "email", "password"]
    #パスワードを暗号化
    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data["password"], user)
        user.set_password(self.cleaned_data["password"])
        user.save()
        return user

UD_CBV/accounts/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, FormView
from django.views.generic.base import TemplateView, View
from .forms import RegistForm
# Create your views here.


class HomeView(TemplateView):
    template_name = "home.html"

class RegistUserView(CreateView):
    template_name = "regist.html"
    form_class = RegistForm
    
class UserLoginView(FormView):
    pass

class UserLogoutView(View):
    pass

UD_CBV/accounts/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="{% url 'accounts:home' %}">ホーム</a>
{% if user.is_authenticated %}
<a class="navbar-brand" href="{% url 'accounts:user_logout' %}">ログアウト</a>

{% else %}
<a class="navbar-brand" href="{% url 'accounts:user_login' %}">ログイン</a>
<a class="navbar-brand" href="{% url 'accounts:regist' %}">ユーザー登録</a>


{% endif %}
</nav>
{% block content %}

{% endblock content %}

    
</body>
</html>

UD_CBV/accounts/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>ホーム画面です</h1>
{% endblock content %}

UD_CBV/accounts/templates/regist.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="ユーザ登録">
</form>
{% endblock content %}